# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Train test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [10]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [11]:
len(df.columns)

31

In [12]:
len(X_train) + len(X_test)

569

In [13]:
X_train

array([[-1.22965126, -0.25073116, -1.26539897, ..., -1.76996072,
        -1.57200667, -1.04530332],
       [-1.38257251, -1.30198443, -1.32741942, ..., -0.98713453,
         0.59421401,  0.04964894],
       [-1.18603935, -0.47978864, -1.1766246 , ..., -0.91003685,
         0.13193968, -0.57976432],
       ...,
       [-0.27074837, -0.94513699, -0.26901811, ..., -0.27386553,
         1.48878585,  0.13073551],
       [ 0.45052553, -1.92405632,  0.43996078, ...,  0.46448714,
        -0.54963886, -0.12556611],
       [ 1.69458322,  0.06753817,  1.69658432, ...,  1.5740167 ,
         0.19978199, -0.18567224]], shape=(455, 30))

In [14]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1])

In [15]:
X_train

array([[-1.22965126, -0.25073116, -1.26539897, ..., -1.76996072,
        -1.57200667, -1.04530332],
       [-1.38257251, -1.30198443, -1.32741942, ..., -0.98713453,
         0.59421401,  0.04964894],
       [-1.18603935, -0.47978864, -1.1766246 , ..., -0.91003685,
         0.13193968, -0.57976432],
       ...,
       [-0.27074837, -0.94513699, -0.26901811, ..., -0.27386553,
         1.48878585,  0.13073551],
       [ 0.45052553, -1.92405632,  0.43996078, ...,  0.46448714,
        -0.54963886, -0.12556611],
       [ 1.69458322,  0.06753817,  1.69658432, ...,  1.5740167 ,
         0.19978199, -0.18567224]], shape=(455, 30))

In [16]:
type(y_train)

numpy.ndarray

In [17]:
type(y_test)

numpy.ndarray

# Numpy Array to tensors

In [18]:
#numpy to tensor
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

#change dtype
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

#numpy to tensor
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

# y_test_tensor = torch.from_numpy(y_test)

/tmp/ipykernel_266743/3826779354.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
/tmp/ipykernel_266743/3826779354.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
/tmp/ipykernel_266743/3826779354.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
/tmp/ipykernel_266743/3826779354.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

In [19]:
type(X_train_tensor)

torch.Tensor

# Dataset and Dataloader

In [20]:
from torch.utils.data import Dataset,DataLoader

In [21]:
class CustomDataset(Dataset):
  def __init__( self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):
    return self.features[index], self.labels[index]

In [22]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [23]:
len(train_dataset)

455

In [24]:
train_dataset[2]

(tensor([-1.1860, -0.4798, -1.1766, -1.0030,  0.9134, -0.6149, -0.8926, -0.7611,
          0.4273, -0.0064, -0.6689,  0.2116, -0.6474, -0.5900,  0.8543, -0.7429,
         -0.7802, -0.6987,  0.1694, -0.4940, -1.1936, -0.4090, -1.1788, -0.9548,
          0.4049, -0.8539, -1.0394, -0.9100,  0.1319, -0.5798]),
 tensor(0.))

#loader

In [25]:
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32,shuffle=True)

# Defining the Model

In [26]:
X_train.shape[1]

30

In [27]:
import torch.nn as nn

In [28]:
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [29]:
torch.rand(30,1)

tensor([[0.5353],
        [0.3027],
        [0.0470],
        [0.5568],
        [0.8084],
        [0.6014],
        [0.6533],
        [0.7795],
        [0.4688],
        [0.7671],
        [0.1235],
        [0.9548],
        [0.9738],
        [0.4484],
        [0.5085],
        [0.6300],
        [0.5811],
        [0.0597],
        [0.6855],
        [0.7175],
        [0.1137],
        [0.6227],
        [0.9976],
        [0.1476],
        [0.7397],
        [0.3387],
        [0.7373],
        [0.8395],
        [0.0911],
        [0.9359]])

# Parameters

In [30]:
X_train_tensor.shape[1]

30

In [31]:
learning_rate = 0.1
epochs = 25

In [32]:
loss_function = nn.BCELoss()

In [33]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [34]:
model = MySimpleNN(X_train_tensor.shape[1])

In [55]:
# Total number of trainable parameters
trainable_parameters = 0
for p in model.parameters():
  # print(p)
  if p.requires_grad:
    # print(p)
    # print(p.numel())
    trainable_parameters += p.numel()

print(trainable_parameters)

# total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
# print(total_params)

31

In [35]:
model.parameters()

In [36]:
X_test_tensor.dtype

torch.float32

In [37]:
model.linear.weight.dtype

torch.float32

In [38]:
y_train_tensor.dtype

torch.float32

In [39]:
model.parameters()

# Training Pipeline

In [40]:
learning_rate = 0.1
epochs = 25
loss_function = nn.BCELoss()

#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop

for epoch in range(epochs):

  for batch_feature,batch_labels in train_loader:
    #forward pass
    y_pred = model(batch_feature)
    #Loss calculate
    loss = loss_function(y_pred,batch_labels.reshape(-1,1))

    #zero gradient
    optimizer.zero_grad()
    #backward pass
    loss.backward()

    #parameter update
    optimizer.step()



  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.1273743361234665
 2 , Loss = 0.29694056510925293
 3 , Loss = 0.060091983526945114
 4 , Loss = 0.015772605314850807
 5 , Loss = 0.12297037988901138
 6 , Loss = 0.11657987534999847
 7 , Loss = 0.07965771108865738
 8 , Loss = 0.03997066617012024
 9 , Loss = 0.341953307390213
 10 , Loss = 0.14479108154773712
 11 , Loss = 0.020730165764689445
 12 , Loss = 0.03581293299794197
 13 , Loss = 0.036693841218948364
 14 , Loss = 0.01618715189397335
 15 , Loss = 0.09240199625492096
 16 , Loss = 0.06497152149677277
 17 , Loss = 0.3513244688510895
 18 , Loss = 0.04246034845709801
 19 , Loss = 0.002854350721463561
 20 , Loss = 0.008584286086261272
 21 , Loss = 0.0748085230588913
 22 , Loss = 0.11270450800657272
 23 , Loss = 0.007350618951022625
 24 , Loss = 0.14464008808135986
 25 , Loss = 0.12318803369998932

# Training pipeline version 2

In [ ]:
learning_rate = 0.1
epochs = 25
loss_function = nn.BCELoss()

#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop
batch_size = 32
epoch = 25
n_sample = len(X_train_tensor)

for epoch in range(epochs):

  for start_indx in range(0,n_sample,batch_size):
    end_indx = start_indx + batch_size

    print(f" Start index {start_indx}, end indx {end_indx}\n")

    X_batch = X_train_tensor[start_indx:end_indx]
    y_batch = y_train_tensor[start_indx:end_indx]

    #forward pass
    y_pred = model(X_batch)
    loss = loss_function(y_pred,y_batch.reshape(-1,1))


    #upate step

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()



  #print loss in each epoch

  # print(f" {epoch+1} , Loss = {loss.item()} ")

# Model Evaluation (old)

In [42]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred= (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f" Accuracy = {accuracy.item()}")

 Accuracy = 0.5495536923408508

# Better version

In [72]:
y_pred.shape

torch.Size([18, 1])

In [73]:
batch_labels.shape

torch.Size([18])

In [80]:
model.eval()  #evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.5).float()

    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()

    accuracy_list.append(batch_accuracy)


overall_accuracy = sum(accuracy_list) / len(accuracy_list)

print(overall_accuracy)

0.9765625

In [75]:
accuracy_list

[0.90625, 0.9375, 0.90625, 0.9444444179534912]

# Summary

In [46]:
X_train_tensor.shape

torch.Size([455, 30])

In [47]:
!pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [48]:
from torchinfo import summary

In [49]:
summary(model, input_size = (455,30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================